// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace toner_API.Models
{
    public partial class Users
    {
        public Users()
        {
            Carga = new HashSet<Carga>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Pass { get; set; }
        public int IdRol { get; set; }

        public virtual Rol IdRolNavigation { get; set; }
        public virtual ICollection<Carga> Carga { get; set; }
    }
}